name: ChipSeq
channels:
   - bioconda
   - conda-forge
   - r
   - bioinfo
dependencies:
   - snakemake-minimal =5.10.0
   - python =3.6
   - fastqc =0.11.9
   - deeptools =3.3.2
   - trimmomatic =0.39
   - bwa =0.7.17
   - segemehl =0.3.4
   - samtools =1.10
   - macs2 =2.2.6
   - ucsc-wigtobigwig =377
   - meme =5.1.0
